title: zamharira
email: zamharil23919@gmail.com
description: >
  Selamat datang di blog pribadi saya, tempat di mana saya menuangkan cerita, inspirasi, dan perjalanan saya sebagai mahasiswa yang selalu ingin berkembang. Di sini, saya berbagi tentang kehidupan kampus, pengembangan diri, produktivitas, serta hal-hal kecil yang membuat hidup lebih bermakna

url: "https://zamharira09.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag